### PR TITLE
hw-mgmt: thermal: Add dynamic module sensor scan

### PR DESCRIPTION
**Pull request by sholeksandr**
Add dynaic sfp module add/remove.

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by ciju-nvidia — APPROVED** [review]

**Pull request merged**
