### PR TITLE
hw-mgmt: sensors: Adjust fan labels for MSN2010, MSN2100 and MSN2410 …

### PR DESCRIPTION
**Pull request by felixradensky**
…systems

Adjust chassis fan labels for MSN2010, MSN2100 and MSN2410 systems to match fan labels for other systems.

Fixes: #3733632

### CODE REVIEW

**Comment by felixradensky** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Pull request merged**
