### PR TITLE
kernel patches: 5.10: Add support for clearing leakage sensor status

### PR DESCRIPTION
**Pull request by felixradensky**
Signed-off-by: Felix Radensky <fradensky@nvidia.com>

### CODE REVIEW

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Review by mshych — APPROVED** [review]

**Review by vadimp-nvidia — COMMENTED** [review]
Should we update patches following after this one?

**Comment by felixradensky** [comment]
> 

This PR updates 2 patches that touch mlx-platform.c driver. Subsequent patches do not touch this driver.

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Pull request merged**
