### PR TITLE
hw-mgmt: patch 5.10: replace frequent pr_info to pr_devel in ICP201xx driver

### PR DESCRIPTION
**Pull request by mshych**
Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Review by MellanoxBSP — APPROVED** [review]

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request closed without merging**
