### PR TITLE
hw-mgmt: devtree scripts: add SMBIOS BOM support for MSN27002. Common SMBIOS BOM improvements.

### PR DESCRIPTION
**Pull request by mshych**
1. Add SMBIOS BOM mechanism support for MSN27002 (Panther-Comex) support
2. Add check for not defined in layout/ignored components.
3. logs improvement.

Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by mshych** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by sholeksandr — APPROVED** [review]

**Pull request merged**
