### PR TITLE
hw-mgmt: events: Add cleanup code for module and cables counters

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Cleanup counters on exit.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by MellanoxBSP** [comment]
RERUN

**Review by mshych — APPROVED** [review]

**Pull request merged**
