### PR TITLE
V.7.0020.2100 BR

### PR DESCRIPTION
**Pull request by mshych**
- hw-mgmt: kernels & scripts: SN2201 fixes and additions.
- hw-mgmt: kernels & script: fix CPLD PN representation on SN2201.

### CODE REVIEW

**Review by yyehudai — APPROVED** [review]
imported from 7.0020.2000

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Pull request merged**
