### PR TITLE
Capturing cpld dump in the hw-management dump

### PR DESCRIPTION
**Pull request by ciju-nvidia**
This patch adds the support for cpld dump capture in the hw-management dump generation script.

Signed-off-by: Ciju Rajan K <crajank@nvidia.com>

### CODE REVIEW

**Comment by ciju-nvidia** [comment]
RERUN

**Review by felixradensky — COMMENTED** [review]
Hi Ciju,
This change will not work on ARM where iorw is not available, you should use iorw.sh instead

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Review by felixradensky — APPROVED** [review]

**Pull request merged**
