### PR TITLE
hw-mgmt: scripts: add conversion of SMBIOS alternative BOM devtree file to csv format.

### PR DESCRIPTION
**Pull request by mshych**
Add possibility to convert devtree and devtree_codes files that are created during
SMBios BOM string parsing to csv file.
This file can be opened later in Excel in order to compare with original design.

Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Review by ciju-nvidia — DISMISSED** [review]
Looks good.

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Pull request merged**
