### PR TITLE
V.7.0040.2000 br merge

### PR DESCRIPTION
**Pull request by sholeksandr**
Merge V.7.0040.1500_for_QS ещ V.7.0040.2000_BR

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Review by acoifmannvidia — COMMENTED** [review]
ok

**Pull request merged**
