### PR TITLE
Fixing the lintian package issue

### PR DESCRIPTION
**Pull request by ciju-nvidia**
The following changes are made:
 - Fix for lintian package download (Ticket: 1639973)
 - Restricting package builds only for a published
   release.

Signed-off-by: Ciju Rajan K <crajank@nvidia.com>

### CODE REVIEW

**Review by vadimp-nvidia — APPROVED** [review]

**Review by sholeksandr — APPROVED** [review]

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Pull request merged**
