### PR TITLE
hw-mgmt: patches: kernel 5.10/6.1: Fix N51XX platform patch Reduce (remove unused) regio attributes to not exeed maximum (96)

### PR DESCRIPTION
**Pull request by sholeksandr**
Bug: 31993608

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by ciju-nvidia — APPROVED** [review]

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
