### PR TITLE
hw-mgmt: patches 4.19: Add support for new feature provided by MTMP

### PR DESCRIPTION
**Pull request by mlnxmykolak**
Signed-off-by: Mykola Kostenok <c_mykolak@nvidia.com>

### CODE REVIEW

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by mlnxmykolak** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by mlnxmykolak** [comment]
RERUN

**Comment by mlnxmykolak** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by mlnxmykolak** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
