### PR TITLE
hw-mgmt: topology: Add COMEX BRDWL respin support

### PR DESCRIPTION
**Pull request by sholeksandr**
1. Removed A2D sensor from all COMEX BRDWL boards
2. Add COMEX BRDWL boards with register defined (config3)
support of TPS/XPDE/MPS voltmon

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Pull request merged**
