### PR TITLE
hw-mgmt: kernel patches: Sync kernel config flags with Readme

### PR DESCRIPTION
**Pull request by sholeksandr**
Sync kernel config flags with Readme

Reviewed-by: Vadim Pasternak <vadimp@nvidia.com>
Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
