### PR TITLE
hw-mgmt: Fix calculation of the number of ASICs on XDR systems

### PR DESCRIPTION
**Pull request by felixradensky**

### CODE REVIEW

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by btamish** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by yyehudai — APPROVED** [review]

**Pull request merged**
