### PR TITLE
hw-mgmg: patches: 5.10: Update register map

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Rebase follwing after patches: #0158 - #0160.
Add patch #0161.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by mshych — APPROVED** [review]

**Pull request merged**
