### PR TITLE
Minor amendments and cosmetic changes

### PR DESCRIPTION
**Pull request by mshych**
Change criteria for matching between cooling level
to be set and current cooling level: from 'le' to 'lt'.

Cosmetic changes for comments.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by MellanoxBSP — APPROVED** [review]

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by MellanoxBSP — APPROVED** [review]

**Comment by MellanoxBSP** [comment]
RERUN

**Comment by mshych** [comment]
CLOSE

**Pull request closed without merging**
