### PR TITLE
hw-mgmt: patches: 5.10: Add patches for SN4800 support

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Update patch #0151.
Rebase patches #0155, #0156.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by felixradensky — APPROVED** [review]

**Comment by felixradensky** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Pull request merged**
