### PR TITLE
hw-mgmt: thermal: Update ambiant sensor logic

### PR DESCRIPTION
**Pull request by sholeksandr**
1. If one of amb_sensor read error - ignore it and set "sensor_read" error
   (after 3 times)
2. If >1 of amb sensors read error - set PWM to max (100%)

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by felixradensky — COMMENTED** [review]
Please fix subject: abiant -> ambiant

**Review by mshych — APPROVED** [review]

**Pull request merged**
