### PR TITLE
hw-mgmt: sensors: Fix configuration for P4262

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Remove empty labels.
Fix hotswap config.

### CODE REVIEW

**Review by mshych — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by sholeksandr — APPROVED** [review]

**Pull request merged**
