### PR TITLE
hw-mgmt: init: Optimize pre-init sequence

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Optime pre-init sequence and avoid endless loop.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by felixradensky — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
