### PR TITLE
hw-mgmt: patches 5.10: Add and modfiy patches

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Modify #0274.
Add #0278.

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by mshych — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
