### PR TITLE
hw-mgmt: patches: Change dpu attribute permission

### PR DESCRIPTION
**Pull request by ciju-nvidia**
This patch gives read permission for dpu[1-4]_pwr, dpu[1-4]_pwr, dpu[1-4]_rst attributes.

Bugs #4023734

### CODE REVIEW

**Comment by ciju-nvidia** [comment]
RERUN

**Review by mshych — APPROVED** [review]

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Pull request merged**
