### PR TITLE
hw-mgmt: scripts: define I2C CPU brd offset in P4262 system.

### PR DESCRIPTION
**Pull request by mshych**
Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Review by felixradensky — APPROVED** [review]

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Pull request merged**
