### PR TITLE
hw-mgmt: Move duplicated functions to separate helper file

### PR DESCRIPTION
**Pull request by sholeksandr**
Move duplicated functions from .sh scripts to separate hw-management-helper.sh file

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — DISMISSED** [review]

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Pull request merged**
