### PR TITLE
V.7.0020.4100 BR

### PR DESCRIPTION
**Pull request by sholeksandr**
- hw-mgmt: psu: Add psuX_fan_dir attribute
- hw-mgmt: fan: Fix fan dir attribute for systems without CPLD fan direction attribute
- hw-mgmt: psu: Fix wrong direction in psuX_fan_dir attribute
- Fix unknown FAN dir for fixed systems with the custom PN
- hw-mgmt: kernel patches: Add patches for fan speed fix
- hw-mgmt: scripts: fix cpu_core temperature links creation.
- hw-mgmt: psu: Add reporting of Delta PSU primary FW version
- hw-mgmt: psu: Fix reporting of Delta 550 FW version
- Capturing cpld dump in the hw-management dump
- hw-mgmt: debug: Add vpd binary dump
- hw-mgmt: Add command to expose reset cause

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by ciju-nvidia — APPROVED** [review]

**Pull request merged**
