### PR TITLE
hw-mgmt: kernel & scripts: add CPLD PN report on SN2201 system

### PR DESCRIPTION
**Pull request by mshych**
Rebase nvsw_sn2201 driver patches for PN report.
Change scripts for CPU CPLD PN report.

Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Pull request merged**
