### PR TITLE
hw-mgmt: scripts: add fan direction indication on SN2201

### PR DESCRIPTION
**Pull request by mshych**
Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
