### PR TITLE
Fix voltmon sensors linking by their labels for mp2975.

### PR DESCRIPTION
**Pull request by sholeksandr**
vin/vin1 -> voltmon_in1_input
vout/vout1 -> voltmon_in2_input
vout2 -> voltmon_in3_input

iin/iin1 -> voltmon_curr1_input
iout/iout1 -> voltmon_curr2_input
iout2 -> voltmon_curr3_input

pin/pin1 -> voltmon_power1_input
pout/pout1 -> voltmon_power2_input
pout2 -> voltmon_power3_input

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Review by felixradensky — COMMENTED** [review]
There are unrelated changes in this commit, related to CPLD handling

**Comment by sholeksandr** [comment]
RERUN

**Review by felixradensky — COMMENTED** [review]
Hi Sasha,
There still some CPLD related modifications in this commit:
https://github.com/Mellanox/hw-mgmt/pull/471/commits/1aaa887e7387889f26cffc1e6ed3d308d8fcf135
Please check.

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
