### PR TITLE
hw-mgmt: scripts: fix cpu_core temperature links creation.

### PR DESCRIPTION
**Pull request by mshych**
Denverton CPU on SN2201 has ridiculous CPU Core numbers 6, 12 instead 0, 1
These core id numbers also can differ in various CPU batches.
This was fixed in later version of coretemp driver e.g. in kernel 5.10.162
and core temperature is reported as in other Intel CPUs, core0 - temp2_input
core1 - temp3_input. Check this case and don't always apply workaround.

Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Review by yyehudai — APPROVED** [review]

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Pull request merged**
