### PR TITLE
hw-mgmt: patches: 6.1: Update kernel patches

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Update and add kernel patches and modify table.

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by shaiazulay** [comment]
RERUN

**Comment by shaiazulay** [comment]
RERUN

**Review by felixradensky — APPROVED** [review]

**Pull request merged**
