### PR TITLE
hw-mgmt: patches: v6.1: Add AMD master/slave driver

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Add patch for AMD/ASF master/slave SMBus driver.

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by ciju-nvidia — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by mshych** [comment]
NV-OS on Juliet will still have 5.10, not 6.1

**Comment by vadimp-nvidia** [comment]
I know.
It’s simple to port it to 5.10.
Big problem with mctp support in 5.10.
I don’t want to take porting on us, but not sure Oren will take it.

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by btamish** [comment]
RERUN

**Pull request merged**
