### PR TITLE
hw-mgmt: kernel patches: Add patch for extending hotplug confuguration

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Currently hotplug configuration in logic device assumes that all items are provided with no holes.
Thus, any group of hotplug events, associated with the specific status/event/mask registers is configured in those registers successively from bit zero to bit #n (#n < 8).

This logic is changed int order to allow non-successive definition to support configuration with the skipped bits – for example bits 3, 5, 7 in status/event/mask registers can be associated with hotplug events, while others can be skipped.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by mshych — DISMISSED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by mshych — APPROVED** [review]

**Pull request merged**
