### PR TITLE
hw-mgmt: thermal: Add new system support to TC

### PR DESCRIPTION
**Pull request by sholeksandr**
Add msn3750 system support to TC

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by yyehudai — COMMENTED** [review]
confirmed

**Pull request merged**
