### PR TITLE
hw-mgmt: patches: 4.19/5.10: Align SN2201 power and platform drivers with accepted upstream code.

### PR DESCRIPTION
**Pull request by mshych**
Allign, bacport following SN2201 patches:
4.19:
	0147-hwmon-powr1220-Upgrade-driver-to-support-hwmon-info-.patch
	0148-hwmon-powr1220-Add-support-for-Lattice-s-POWR1014-po.patch
	0149-platform_data-mlxreg-Add-field-for-notification-call.patch
	0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
	0153-Documentation-ABI-Add-new-attributes-for-mlxreg-io-s.patch
5.10:
	0083-platform_data-mlxreg-Add-field-for-notification-call.patch
	0085-hwmon-powr1220-Upgrade-driver-to-support-hwmon-info-.patch
	0086-hwmon-powr1220-Add-support-for-Lattice-s-POWR1014-po.patch
	0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
	0090-Documentation-ABI-Add-new-attributes-for-mlxreg-io-s.patch

Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Review by ciju-nvidia — APPROVED** [review]

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
