### PR TITLE
V.7.0030.1000 BR

### PR DESCRIPTION
**Pull request by sholeksandr**
- hw-mgmt: thermal: Fix TC close flow
- hw-mgmt: thermal: Fix TC start on SPC1 systems

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by ciju-nvidia — APPROVED** [review]

**Pull request merged**
