### PR TITLE
hw-mgmt: kernel patches: Add patches for dynamic I2C bus allocation

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
…nd extra I2C features

Add patches #0187 - #0196.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by mshych — APPROVED** [review]

**Pull request merged**
