### PR TITLE
Merge branch 'V.7.0010.3300_DNI_BR' into V.7.0020.1200_BR

### PR DESCRIPTION
**Pull request by sholeksandr**

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by mshych — APPROVED** [review]

**Review by mshych — APPROVED** [review]
Approved

**Pull request merged**
