### PR TITLE
hw-mgmt: thermal: Change TC error handling for PSU FAN "unknown" direction

### PR DESCRIPTION
**Pull request by sholeksandr**
In case we can't recognize PSU FAN dir by PSU PN match, psu_fan_dir
attribute will be set to "unknown" state (psu_fan_dir value == 2).

Therma algo will not treat this "unknown" direction as an error.

bug #3706151

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Pull request merged**
