### PR TITLE
V.7.0030.3000 BR

### PR DESCRIPTION
**Pull request by sholeksandr**
- hw-mgmt: thermal: Add links to BF3 core_temp/ddr_temp temperature
- hw-mgmt: thermal: TC add sensor *_scale support

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by yyehudai — APPROVED** [review]

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
