### PR TITLE
hw-mgmt: debug: Add timeout to generate-dump.sh

### PR DESCRIPTION
**Pull request by sholeksandr**
Add timeout to generate-dump.sh

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Review by vadimp-nvidia — COMMENTED** [review]
Sasha, why we need timeouts. Is it some case when we can't generate something and hang?

**Comment by sholeksandr** [comment]
https://redmine.mellanox.com/issues/2754604
On ASIC FW stuck we have some commands hang in debug-dump like 'sensors', reading sfp, etc...

Best Regards,
Oleksandr Shamray
NVIDIA<http://www.nvidia.com/>

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by vadimp-nvidia** [comment]
RERUN

**Pull request merged**
