### PR TITLE
Disable hw-mgmt on SimX platforms

### PR DESCRIPTION
**Pull request by ciju-nvidia**
This patch disables the hw-mgmt and hw-mgmt-tc
on the platforms where BSP platform emulation is
not supported.

### CODE REVIEW

**Review by yyehudai — APPROVED** [review]

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by ciju-nvidia** [comment]
RERUN

**Pull request merged**
