### PR TITLE
hw-mgmt: attributes: add separate function for link/unlink sysfs attributes

### PR DESCRIPTION
**Pull request by sholeksandr**
To optimize source code  size and quality - add separate functions for check and create/delete
link for sysfs attributes.

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Review by vadimp-nvidia — DISMISSED** [review]
The change look fine and it reduces the size of scripts.

Is it just improvement or you also wants to solve some issues?

**Comment by sholeksandr** [comment]
It's preparation for next feature request. We plan to add links to psu volt/current/power critical attributes. And for each _crit attribute we need to check if it exists. So this current commit need o minimize size in future

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
