### PR TITLE
hw-mgmt: scripts: make ii0 a2d link just in case that file exist.

### PR DESCRIPTION
**Pull request by mshych**
This iio udev trigger is mixed-up on Moose system with iio pressure sensor.

Signed-off-by: Michael Shych <michaelsh@nvidia.com>

### CODE REVIEW

**Review by felixradensky — APPROVED** [review]

**Comment by felixradensky** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Pull request merged**
