### PR TITLE
hw-mgmt: devtree: Fix detection of new device categories

### PR DESCRIPTION
**Pull request by felixradensky**
Earlier patch that introduced detection of new device categories has used wrong counter variable for each new category. Fix that by adding new counter variable for each new category.

### CODE REVIEW

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Comment by felixradensky** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Pull request merged**
