### PR TITLE
hw-mgmt: scripts: add new reset ready attribute.

### PR DESCRIPTION
**Pull request by mshych**
New reset_attr_ready file is created and set to 1 when all reset cause links
for this system are created. It can be used as a trigger in other services
that they can check reset reason.

Reviewed-by: Vadim Pasternak <vadimp@nvidia.com>
Signed-off-by: Michael Shych <mshych@nvidia.com>

### CODE REVIEW

**Comment by mshych** [comment]
RERUN

**Comment by mshych** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by sholeksandr — APPROVED** [review]

**Pull request merged**
