### PR TITLE
hw-mgmt: thermal: Fix thermal data for MSN4700

### PR DESCRIPTION
**Pull request by sholeksandr**
Fix thermal data for msn4700 system equipped with mps2975 voltmon

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Review by ciju-nvidia — APPROVED** [review]

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by libermanor** [comment]
RERUN

**Comment by libermanor** [comment]
RERUN

**Pull request merged**
