### PR TITLE
hw-mgmt: thermal: Add "hotswap" and "bmc" TC sensor support

### PR DESCRIPTION
**Pull request by sholeksandr**
1. Add "hotswap" and "bmc" TC sensor support

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by felixradensky — APPROVED** [review]

**Pull request merged**
