### PR TITLE
hw-mgmt: patches: Update ASF I2C patch

### PR DESCRIPTION
**Pull request by vadimp-nvidia**

### CODE REVIEW

**Review by mshych — APPROVED** [review]

**Comment by shaiazulay** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by shaiazulay** [comment]
RERUN

**Comment by shaiazulay** [comment]
RERUN

**Comment by shaiazulay** [comment]
RERUN

**Comment by shaiazulay** [comment]
RERUN

**Pull request merged**
