### PR TITLE
master

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
- hw-mgmt: topology: Extend support for mqm9700 system (#186)
- hw-mgmt: patches: v5.10: mlxsw: Add support for transceiver modules reset and power mode

### CODE REVIEW

**Review by mshych — APPROVED** [review]

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
