### PR TITLE
hw-mgmt: scripts: Update SimX supported platforms

### PR DESCRIPTION
**Pull request by ciju-nvidia**
This commit adds the smart switch (SN4280) to SimX support list.

### CODE REVIEW

**Comment by ciju-nvidia** [comment]
RERUN

**Review by vadimp-nvidia — APPROVED** [review]

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Pull request merged**
