### PR TITLE
hw-mgmt: patches: 5.10: Align ethtool UAPI interface with upstream

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Update patches #0076 and #0080 to match upstream.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by sholeksandr — APPROVED** [review]

**Pull request merged**
