### PR TITLE
hw-mgmt: init: Store retry counter in file

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Use file system to store ASIC retry counter, instead of reading it from the stack.

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RETRY

**Review by mshych — APPROVED** [review]

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by ciju-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Pull request closed without merging**
