### PR TITLE
hw-mgmt: thermal events: Fix symbolic link creation for gearboxes

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Fix broken index for gearbox temprature symbolic link.
Read this index from gearbox counter.

Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by sholeksandr — APPROVED** [review]

**Pull request merged**
