### PR TITLE
hw-mgmt; patches: Align kernel with after BF3 bring-up

### PR DESCRIPTION
**Pull request by vadimp-nvidia**
Rebase patches accroding to up-streaming order.

### CODE REVIEW

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Comment by vadimp-nvidia** [comment]
RERUN

**Review by felixradensky — APPROVED** [review]

**Pull request merged**
