### PR TITLE
hw-mgmt: topology: Fix n5110_LD TTM fan/drwr count

### PR DESCRIPTION
**Pull request by sholeksandr**
Fix n5110_LD TTM fan/drwr count

fan = 8
drwr = 4

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Review by yyehudai — APPROVED** [review]

**Pull request merged**
