### PR TITLE
hw-mgmt: patches: Add upstream/downstream option to patch_deploy_tool

### PR DESCRIPTION
**Pull request by sholeksandr**
Add config option "--config_file_downstream" for create separate upstream/downstream
.config kernel configuration:

  --config_file CONFIG_FILE
                        Will update kernel CONFIG with the all flags.
                        In case of using together with --config_file_downstream argument - will be copied
                        only CONFIG_(s) marked as upstream (default: None)
  --config_file_downstream CONFIG_FILE_DOWNSTREAM
                        Will update kernel CONFIG with the flags related only to  downstream configuration.
                        In case this argument is missing - all CONFIG_* options will be passed
                        to file specified in --config_file argument
                        This argument can be used only together with --config_file (default: None)

Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>

### CODE REVIEW

**Review by vadimp-nvidia — APPROVED** [review]

**Review by yyehudai — APPROVED** [review]

**Comment by yyehudai** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Comment by sholeksandr** [comment]
RERUN

**Pull request merged**
